Pessoa:
  connection: teste
  tableName: pessoa
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nome:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    dt_nascimento:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sexo:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
